import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, BrainCircuit, CalendarDays, CheckCircle2, ChevronRight, GitBranch, LockKeyhole, Menu, MessageSquare, ShieldCheck, Sparkles, X } from 'lucide-react';
import './styles.css';
const Github = GitBranch;

type Page = 'home' | 'projects' | 'interview';
const projects = {
  jianli: { name: 'AI 面试协作站', tag: 'AI Agent 全栈产品', summary: '把“看简历、追问项目、约面试”串成一条可验证的产品链。', proof: ['RAG + L1 Persona', '预约事务与 Outbox', 'SSE 断线恢复'], decisions: ['Agent 只问答，不直接写预约', 'Slot 行锁保证改期原子性', '投递目的与业务事件解耦'] },
  sleep: { name: 'Sleep AIoT Agent', tag: 'Agent 工程与边缘计算', summary: '把睡眠健康场景做成受治理的 Agent 系统，而不是套一个聊天框。', proof: ['Agent 回归 84/84', 'Prompt Injection 0 次越权', 'React / NestJS / Python / MQTT'], decisions: ['route → policy → finalize', '高影响工具需要人工审批', 'RAG 无证据时返回 grounded=false'] },
};

function Shell({ page, setPage }: { page: Page; setPage: (p: Page) => void }) {
  const [menu, setMenu] = useState(false);
  return <header className="topbar"><button className="brand" onClick={() => setPage('home')}><span className="brand-mark">晓</span><span>用户的 AI 工作台</span></button><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label="打开导航">{menu ? <X/> : <Menu/>}</button><nav className={menu ? 'nav open' : 'nav'}>{[['home','问答入口'],['projects','项目证据'],['interview','预约面试']].map(([id,label]) => <button key={id} className={page===id?'active':''} onClick={() => {setPage(id as Page);setMenu(false)}}>{label}</button>)}</nav><div className="availability"><span/> 当前可交流</div></header>
}

function Home({ setPage }: { setPage: (p: Page) => void }) { const [q,setQ]=useState(''); return <main className="home page"><section className="intro"><p className="eyebrow"><Sparkles size={15}/> AI 全栈开发工程师 · Agent 方向</p><h1>先看证据，再聊实现。</h1><p className="lede">这是一个面向面试官的可验证简历入口。你可以直接追问项目决策，也可以先浏览两个完整的 Agent 工程样本。</p><div className="quick-actions"><button className="primary" onClick={()=>setPage('projects')}>查看项目证据 <ArrowUpRight size={17}/></button><button className="secondary" onClick={()=>setPage('interview')}><CalendarDays size={17}/> 预约面试</button></div><div className="signal-row"><span><CheckCircle2/> 设计基线已批准</span><span><ShieldCheck/> 边界清晰</span><span><Github/> 证据可追溯</span></div></section><section className="qa-panel"><div className="panel-head"><div><span className="status-dot"/> 简历问答</div><span className="muted">静态展示壳</span></div><div className="conversation"><div className="bubble assistant"><BrainCircuit size={18}/><div><b>你好，我是用户的数字分身。</b><p>我可以基于项目证据回答架构、Agent 治理和上线取舍。</p></div></div><div className="suggestions">{['为什么 Agent 不直接预约？','如何保证 RAG 不编造？','通知失败怎么重试？'].map(x=><button onClick={()=>setQ(x)} key={x}>{x}<ChevronRight size={15}/></button>)}</div></div><div className="composer"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="输入你想追问的项目问题…"/><button aria-label="发送问题"><ArrowUpRight size={19}/></button></div><p className="hint"><LockKeyhole size={13}/> 当前为静态演示，不会发送真实请求</p></section></main> }

function ProjectCard({ id, onSelect }: { id: keyof typeof projects; onSelect: (id: keyof typeof projects)=>void }) { const p=projects[id]; return <article className={'project-card '+id}><div className="card-top"><span className="project-index">0{id==='jianli'?'1':'2'}</span><span className="tag">{p.tag}</span></div><h2>{p.name}</h2><p className="summary">{p.summary}</p><div className="proof-grid">{p.proof.map((x,i)=><div key={x}><strong>{['01','02','03'][i]}</strong><span>{x}</span></div>)}</div><button className="text-button" onClick={()=>onSelect(id)}>展开项目拆解 <ArrowUpRight size={16}/></button></article> }
function Projects() { const [selected,setSelected]=useState<keyof typeof projects>('jianli'); const p=projects[selected]; return <main className="projects-page page"><div className="page-heading"><div><p className="eyebrow">PROJECT EVIDENCE / 02</p><h1>两个项目，回答同一个问题：<em>能否把 Agent 做得可靠？</em></h1></div><p className="heading-note">面试官视角：先看解决了什么，再看如何验证。</p></div><div className="project-layout"><div className="cards"><ProjectCard id="jianli" onSelect={setSelected}/><ProjectCard id="sleep" onSelect={setSelected}/></div><aside className="detail"><div className="detail-kicker"><span className="status-dot"/> {p.tag}</div><h2>{p.name}</h2><p>{p.summary}</p><h3>关键取舍</h3><ul>{p.decisions.map(x=><li key={x}><CheckCircle2 size={16}/>{x}</li>)}</ul><div className="detail-footer"><span>证据等级</span><b>{selected==='jianli'?'设计基线 / 待实现':'本地验证 / 模拟设备'}</b></div></aside></div></main> }
function Interview() { return <main className="interview page"><div className="interview-box"><div className="icon-circle"><CalendarDays/></div><p className="eyebrow">INTERVIEW / 03</p><h1>把讨论留给真正值得的问题。</h1><p>预约能力将在后续版本接入。当前先通过项目页了解工程取舍，避免展示未经验证的可用时段。</p><button className="primary" disabled><MessageSquare size={17}/> 预约功能即将开放</button><span className="muted">不会伪造可用时间或提交真实预约</span></div></main> }
function App(){ const [page,setPage]=useState<Page>('home'); return <><Shell page={page} setPage={setPage}/><div className="desktop-gate"><div><LockKeyhole size={24}/><h2>请使用桌面端访问</h2><p>为保证项目架构与证据布局完整，本展示在 1024px 以下暂不开放。</p></div></div><div className="app-content">{page==='home'?<Home setPage={setPage}/>:page==='projects'?<Projects/>:<Interview/>}</div><footer><span>Jianli · AI 全栈开发工程师</span><span>基于已批准设计基线构建</span></footer></> }
export default App;
createRoot(document.getElementById('root')!).render(<App />);
