"""Canonical 20-document production corpus shared by seeding and frozen RAG tests."""

# ruff: noqa: E501
CANONICAL_CORPUS: dict[str, str] = {
    "profile.md": "# [姓名已脱敏]｜个人档案、教育与能力\n我叫[姓名已脱敏]，[学校已脱敏]计算机科学与技术专业 2026 届本科，专业排名 3/153（前 2%）。求职方向是 AI 全栈/后端与平台工程，意向深圳南山。实习中主要负责云端后端、Agent Runtime 与 RAG，也参与数据链路、多租户治理、联调和产品协作。技术栈包括 Python/FastAPI、NestJS、PostgreSQL/pgvector、Redis、TypeScript/React、LangGraph、Docker、K8s/ArgoCD、Kafka/Flink/ClickHouse；日常在 WSL/Linux 下开发、部署和排查。我偏好先设计后编码，把文档、契约、评测、门禁和可观测性都视为交付物。我适合 AI 全栈、后端与平台工程岗位，尤其适合重视工程质量、技术深度、协作和可交接性的团队；选择公司时看重完整的工程环境、成长空间和技术成长路径，长期目标是成为架构师。",
    "credentials.md": "# 证书、荣誉与竞赛资格证明\n持有 PingCAP TiDB 数据库专员 PCTA 认证证书和大学英语四级 CET4。获得 2025 年国家励志奖学金、2022—2026 校级奖学金、2026 年优秀毕业生；2024 年大学生创新创业训练计划国家级立项第一负责人，并获得挑战杯科技发明制作 A 类赛事路演资格。识别准确率 ≥95% 是红火蚁项目申报书目标指标，不表述为已经实测达到；相关专利属于学校。",
    "litchi-overview.md": "# Litchi Copilot｜项目定位、职责与证据边界\n这是我独立完成的 2026 届毕业设计《基于大模型 RAG 的荔枝智能问答平台设计与实现》，正式成绩 90.4 分。我独立完成 Spring Boot 3.2 / Java 17 后端、Vue3 + TypeScript 前端、Python 诊断服务、知识语料与评测，共 22 个业务页面。平台面向农户、农资门店和农业技术员，把病害线索、资料取证、方案建议、人工确认、门店咨询与反馈放进同一产品；这些模块存在，但缺少统一业务 ID 和强状态关联，因此只能称部分协作闭环。Milvus、Neo4j、Ollama 完整环境由我实际跑通并在答辩现场演示。Kafka/ClickHouse/dbt/Airflow 数据平台、Grafana/Tempo 可观测性和 Helm 是我实现的实验模板，不表述为生产部署或长期在线系统。",
    "litchi-agent-rag.md": "# Litchi Copilot｜受控 Agent、HITL 与 RAG 调用链\nAgentService 的 Planner 让本地 Ollama qwen2.5:0.5b 生成 JSON 计划，解析失败走确定性 fallbackPlan。服务端不信任模型计划：内嵌 Guard 只接受 availableTools，去掉未知和重复工具，再按 AgentTool.supports(user) 收窄角色权限并限制最多 4 步；Executor 顺序执行，Synthesizer 只根据工具证据作答。pending_remedy_plan 写操作先进入 waiting_approval，确认后才落库；但当前同一技术员可以发起并确认，所以是单人显式 HITL，不是双人复核。异步执行使用 JVM 公共线程池，没有专用有界队列；cancel 只改状态，不能中断已经发出的 LLM/数据库调用。\n文档摄入支持 txt/md/csv/json/docx/pdf，经文本抽取和空白归一化后按 480 字符、120 重叠切块。SimpleEmbeddingService 用双字符片段和分词做 Java hash，映射到 1024 维并 L2 归一化；它便于 CPU 离线演示，但不是 BGE 等语义 embedding。查询合并 Milvus 文档候选和本地扫描，按标题、来源、关键词启发式重排，Neo4j 单独补关系证据，再交给本地 Ollama 合成；失败时使用证据模板降级。不能宣称 BM25/RRF、高级 reranker 或 HNSW/IVF 调优。\n一次关键复盘是：初版中文 PDF/DOCX 已在入口解析为空或乱码，我却先去调向量和阈值。当前实现改用 PDFBox 和 Apache POI；有效文本才能产生分块，空分块会明确标成未索引，清洗脚本另把扫描件标为 needs_ocr。历史跨 Windows/容器导入还留下重复状态，当前检索会按文档、来源、标题、页码和内容去重并优先不同来源，但不能说旧状态已经清理干净。",
    "litchi-evidence-retrospective.md": "# Litchi Copilot｜评测、并发、事务与失败复盘\n测试源码已提交；38/38 后端通过和一次 30 分钟、119 轮巡检来自未提交本地报告，证据等级低于可复现提交。60 条评测数据和结构校验已提交，真实 runner 结果在工作区：Agent 20/20、RAG 24/30、安全拒答 0/10，合计约 44/60，gate 失败。Runner 固定技术员上下文，未真实覆盖角色/租户；citation 可被通用词命中，所谓 P95 实际接近样本最大值，成本字段固定为 0，所以结果用于暴露盲区，不是质量证书。同一批 runner 结果对修复前 evidenceIds 只有 3/30，对修复后标注为 24/30；主要变化是纠正权威文档编号，不是检索能力提升八倍，剩余 6 条才是真实未命中。\n历史 50 并发、50 请求全部成功，平均约 6.9 秒、P95 约 11.2 秒；后续 100 并发、200 请求多轮成功率约 50.5%、21% 和 19%，其中一轮 P95 约 15.2 秒。依赖状态、脚本和代码版本没有严格冻结，不能证明单一性能回归根因，只能确认高并发稳定性未达标。Agent 状态与 outbox 不是同一事务；后端提供 SSE 状态端点但当前前端主要轮询。诊断链存在真实模型、数据集演示和后端 fallback 三条路径。原始 11 类 27,594 张图片只抽取五类均衡子集：300 张训练、80 张验证；续训中最佳 Top-1 为 93.75%，最后一轮为 91.25%，部署权重哈希与 best.pt 一致。80 张验证集过小且 epoch 波动明显，只能证明五分类实验链路。当前降级路径仍可能参考文件名提示或数据集原型，但会返回 engine 与 demoMode；只有 ultralytics-yolo 且 demoMode=false 能作为真实模型推理，不能把演示 fallback 混称为模型准确率。",
    "litchi-evolution.md": "# Litchi Copilot｜当前边界与下一版演进（以下方案尚未落地）\n当前 run、step、approval、业务写入和 outbox 没有处在同一个可恢复事务状态机中；状态以内存为主并可写 MySQL JSON 快照，执行中的 steps 不逐步持久化。SSE 事件只在进程内，前端主要轮询；多实例后会先出现续传、丢事件和重复副作用。租户字段存在但默认值和文档 ACL 不能形成强隔离，Agent 使用公共线程池同步调用多个依赖，也没有 Token、成本和全链 deadline。\n下一版按风险排序：先用版本 CAS、幂等 invocation 和真正事务 Outbox 统一状态与事件；用 Redis Stream + Last-Event-ID 恢复断线；再建立 tenant-aware principal、复合租户索引和数据库 RLS；给 Agent 增加专用有界执行器、拒绝策略、每租户配额、deadline/cancellation，并用 JFR/线程转储定位瓶颈。安全侧把输入分类与工具风险策略放到 Planner 前后，并把同人确认升级为职责分离审批。先修评测可信度和恢复，再谈扩模型与工具。",
    "sleep-overview.md": "# 睡眠健康 AI Agent 平台｜项目定位、职责与公开边界\n这是我在泰益智医疗参与的团队项目，面向非接触式毫米波雷达睡眠监测、健康问答和受控设备操作。我主要负责云端后端、Agent Runtime 与 RAG，也参与遥测数据链路、多租户治理、云环境和联调排障；嵌入式固件主要由同事负责，我负责云侧验证与集成。项目确实使用过真实 ESP32/雷达硬件日志，历史 ACK/RDS staging 也由我操作和排障，但受 NDA 约束不公开公司源码、日志、截图、设备标识或客户数据。同一前端代码形成 Taro 小程序、Web 和零自定义原生业务代码的 Capacitor Android 壳。以下必须区分已提交代码、本地验证、未提交 RC、历史staging 和未来方案，不表述为生产上线。",
    "sleep-agent-runtime.md": "# Sleep Agent Runtime｜异步接纳、固定 DAG 与协调器边界\nNestJS 完成 JWT、成员关系和可信 tenant 解析后创建 AgentRun 与 Outbox，再投递到 FastAPI。FastAPI 校验 run_id、输入和容量，保存快照后放入默认容量 1000 的 asyncio.Queue，由默认 10 个 Worker 执行并返回 202；202 只表示接纳，不是执行完成。1000 个本地合成请求、并发 100 时，接纳吞吐 87.78→433.53 次/秒，P95 1347.73→228.85ms；不含真实 LLM、RAG、工具、生产网络或跨 Pod，因此只能说本地异步接纳优化。控制面 Run 与 Outbox 不是同一事务，本地队列也不是持久消息队列。\n任务编排使用 LangGraph route→policy→finalize 固定 DAG，不是开放式 ReAct。状态包含步骤、时间、输入/输出 Token 和工具调用五个预算字段，但部分预算在执行或模型返回后检查，不是严格费用熔断。local coordinator 管进程内队列与 SQLite 恢复；Temporal 代码负责 Workflow、审批/取消信号和 Activity，现有测试使用 Fake Client，不能宣称真实 Worker 中断恢复；PostgreSQL Store 只存快照/Memory/Workspace，没有 CAS，也不替代 Temporal 历史。",
    "sleep-rag-governance.md": "# Sleep 工具、HITL、RAG 与安全可信边界\n六个工具有实际执行代码，但不是模型动态选工具：Agent 类型映射固定计划，policy allowlist 先定义能力，执行器再检查白名单、参数范围和设备列表。device_control 未审批时停在 waiting_approval；NestJS 审批有 JWT、租户成员和角色检查，但 owner/admin/member 都可审批，不是职责分离。关键缺口是控制面没有像睡眠报告那样为 device_control 注入可信设备白名单，执行器在缺少 allowed_device_ids 时又会回退到输入 device_id；因此不能宣称设备归属闭环。Agent Service 内部端点也缺少独立服务身份，主要依赖网络边界。\nRAG 实现文档摄入、基础分块、Embedding、pgvector 余弦检索、global+tenant 过滤、引用和无证据拒答；真实 PostgreSQL 下有 2/2 租户隔离用例和 8/8 确定性契约，但测试 embedding 是固定向量。没有 BM25、Hybrid、RRF、reranker、最小相似度或正式 Recall/MRR。固定工具计划能阻止输入改变工具类型，却不能证明未知 Prompt Injection 或输出 DLP 已解决。",
    "sleep-data-reliability.md": "# Sleep 遥测、Rebalance 与设备命令可靠性\nMQTT→Kafka→Worker/ClickHouse 和 Kafka→Flink→治理主题均有实现与本地证据。Worker 重平衡首轮写入 6,291 行但只有 6,240 个唯一事件，多出的 51 条是错误重复；根因不是网络，而是 ClickHouse Array(UUID) 参数查重静默返回空集。改为 String 数组并在 SQL 内转 UUID 后，三轮均 6,240/6,240、12 分区 lag=0，300 次显式重放全部抑制，恢复中位数 12.605s。计时从 kill 到 lag 首次归零，不是端到端恢复 SLA；环境是本地双 Worker、单 Kafka、单 ClickHouse，不证明 HA、多 AZ 或生产吞吐。\n后端 MQTT command/ACK 路径和固件源码存在，真实硬件联调由本人确认；但公开 Agent Harness 返回 simulated-device ACK。当前仓库每次 HTTP 请求生成新 command_id，没有请求 fingerprint 幂等闭环；迟到 ACK 还可能把 timeout 记录改成 success。公司内部未提交 RC 的指纹、唯一约束和真实 ACK 只能作为 NDA 下的本人经历，不冒充公开仓库可复现实现。",
    "sleep-evidence-retrospective.md": "# Sleep 工程评测与红队｜通过率、失败和证据等级\nHEAD 的 84 条确定性工程用例由源码生成并顺序执行同一固定图，实际是 11 个 case group：睡眠分析 20、知识问答 10、Prompt Injection 10、已审批控制 10、未审批控制 5、模拟超时 5、睡眠报告 5、改善计划 5、语音陪伴 5、算法优化 5、隐私拒绝 4，总计 84/84。为了展示可以归并为七类，但不能说源码原生就是七类。Provider、特征和语料均固定，设备 ACK 是模拟，所以它验证图状态与精确工具序列，不验证真实 LLM、真机或生产安全。\n未提交 RC 扩展为八维指标，健康合规 25/35=71.43%。我与同事共同设计、执行和分析 120 条红队，通过 96/120=80%；24 条失败中主要有 17 条正则输入守卫漏检和 7 条运行边界不符合预期。危险写工具调用为 0 只表示固定工具与审批边界在这些模拟样本中守住，不能抵消输入漏检，也不能称为生产安全率。公开表达必须把 HEAD 的 A 级确定性证据与 RC 的 C 级证据分开。",
    "sleep-evolution.md": "# Sleep Staging、可观测性与下一步演进\n历史 ACK/RDS staging 由我实际操作和排障：阿里云基础设施和数据库迁移跑通过，但应用因启动与扩展能力问题失败，修复候选没有重新部署，因此只能说有真实上云排障经历，不能说staging 成功或生产上线。K8s/IaC 较完整，Helm/GitOps、数据平台和部分可观测能力属于实验模板。当前代码有健康、指标和脱敏 metadata Trace View，但没有 Prometheus 实际抓取、告警触发恢复、跨服务 OpenTelemetry Trace、当前镜像回滚或完整数据面云端 readiness 证据。\n下一版先把 Run 与 Outbox 放入同一事务，建立服务身份和可信设备归属，按接纳/开始/终态拆分 SLI；生产执行只走 Temporal 或持久队列，并真实中断 queued/running/waiting_approval 验证恢复。设备副作用增加 request fingerprint、幂等记录和迟到 ACK 状态守卫；再做双租户负向隔离、跨 Pod 真机闭环、队列年龄/拒绝率告警和不可变镜像回滚。",
    "jianli-overview.md": "# Jianli AI 面试协作站｜从聊天入口到可靠业务闭环\n这是我独立开发、准备挂正式域名上线的求职产品。浏览器通过 React 19 页面调用 FastAPI：公开问题走 SSE，登录用户可持久化本人会话；知识库先按 page/project 域检索，模型只有在有依据时生成并返回引用。预约链路把邮箱验证码登录、动态 Slot、预览确认、并发创建、本人管理、管理员看板、邮件与飞书同步连在一起。数据层使用 SQLAlchemy/Alembic 0010、PostgreSQL 16 + pgvector 和 Redis 7，模型链路为 DeepSeek V4 Flash、BGE-M3 与可选Qwen3-Reranker-8B。核心设计是把概率模型限制在确定性边界内：证据门决定能否回答，服务端白名单与 RBAC 决定能否操作，数据库事务和 Outbox 决定副作用如何落地。",
    "jianli-agent-rag.md": "# Jianli 受控 Agent 与混合 RAG｜检索词失败也不丢证据\n模型以 function calling 自主选择 search_knowledge 并生成检索词，但模型输出不被直接信任：服务端同时检索模型词和用户原问题，按文档与片段去重合并，避免模型改写失真把原始证据裁掉。每一路先做 1024 维 BGE-M3 向量 top10；若没有达到 0.47 的向量候选，即使BM25 有中文单字重叠也拒绝据此硬答。通过证据门后，BM25 top10 与向量结果用 RRF(k=60)融合为最多 12 条，再由可选 Cross-Encoder 排到 top6，并保持 page/project 域隔离。本地哈希 embedding 只是确定性离线 fallback；对照中 BGE-M3 纯向量 avg-rank 1.3，哈希为 1.8。回答流遵守 started→trace/delta→citations→completed；无依据返回 offtopic，不会让模型凭常识补齐个人经历。",
    "jianli-agent-lab.md": "# Jianli Agent Lab｜模型负责规划，代码负责授权\n避免智能体乱调用不能只靠 Prompt：Agent 最多循环 4 步，只注册 search_knowledge、创建预约、查询本人预约、取消本人预约、改期本人预约五个工具；未知工具确定性拒绝。预约工具必须登录，面试官只能操作本人记录，所有写操作复用 BookingService 的校验、事务和审计，模型不能直接写库；管理员管理他人的能力走独立管理端服务边界，不因模型声称自己是管理员而放权。每轮工具结果作为结构化证据交回模型生成自然语言，检索工具则进入 RAG 引用链。页面预置依据问答、多步只读预约、越权攻击、无依据拒答四类真实挑战，调用同一 SSE 接口而非展示预制答案。answer.trace 只公开单调 step、固定 phase/status、白名单工具名、耗时和短标签；不含 Prompt、用户/知识原文、工具参数、完整结果或预约 PII，因此是可审计执行事实，不是模型思维链。",
    "jianli-evaluation-ci.md": "# Jianli 评测中心与 CI 门禁\n评测中心读取版本化 JSON 报告，公开样本数、生成时间、verified commit、套件结果与脱敏边界案例，而不是运行时临时拼一个满分。当前报告为 79/79：Agent/Trace 22、RAG 事实一致性 38、Web 交付 1、Cross-Encoder 协议 4、语义缓存与 Provider 韧性 8、多副本共享熔断 6；真实 RAG 测试会上传 canonical corpus、分块、BGE-M3 embedding 入 pgvector，再验证命中、拒答、隐私和误拒。Agent Quality Gate 定义 backend-agent→rag-integration→web-delivery 三个串行 job，后两段分别带真实 PG/Redis和前端测试/typecheck/build。当前只有本地等价门禁证据，尚无远端 Actions run；79/79 也只是这组冻结检查全过，不等于生产准确率或线上可用性，所以不能说云端流水线已经跑绿。",
    "jianli-observability.md": "# Jianli OpenTelemetry + Prometheus/Grafana\n显式开启后，ASGI 中间件从请求头提取 Trace 上下文，覆盖完整流式响应时长，并只记录method、规范化 route、status。AIQA 另有回答结果/耗时/token、工具结果、重排、语义缓存和LLM/Reranker 熔断指标与 Span event；工具名和状态均为有界标签，未知工具折叠为固定值。Prometheus 通过私网 /internal/metrics 暴露，Nginx 对公网返回 404；配置 OTLP 时批量导出OpenTelemetry，未配置则不外发。Grafana Agent Overview 有 10 个面板。问题、回答、Prompt、知识原文、PII、密钥、高基数 ID 和异常正文不进入观测属性。代码与自动化测试已验证，完整 Collector/Prometheus/Grafana 容器栈 smoke 尚未完成。",
    "jianli-reranker.md": "# Jianli Reranker 对照实验\nCross-Encoder 只接收已经通过域过滤和相关性门槛的 RRF top12，不能扩大召回、跨项目取证或绕过拒答；Qwen3-Reranker-8B 返回排序索引与分数后，服务端再次校验数量、类型、重复和越界索引，最终取 top6。每次检索最多外调一次且超时上限 5 秒；超时、429/5xx、协议畸形或熔断都会 fail-open，完整保留原 RRF 顺序，而不是让问答一起失败。真实 provider 的 5 题组件对照为 MRR 0.3333→1.0000、Hit@1 0/5→5/5；样本很小，只能证明组件排序改善，不能外推端到端生产质量；79/79 版本化检查同样不是生产准确率。",
    "jianli-reliability.md": "# Jianli 可靠业务闭环｜不是只会聊天的 Demo\n预约预览令牌绑定登录人和规范化表单、有效 3 分钟且不占 Slot；确认时在一个事务中锁公司与三个连续 30 分钟 Slot，检查状态后写 appointment、更新 Slot、Outbox 和审计；并发冲突映射为业务错误。改期同样先锁记录和新 Slot，再释放旧 Slot。Slot 竞争靠行锁和事务内复核；活动用户/公司部分唯一索引独立约束重复业务预约，不是所谓‘行锁失效兜底’。敏感字段用带表/列/记录 AAD 的 AES-256-GCM，去重只存 HMAC 指纹。过期 active 状态的预约由幂等 CTE 自动完成并取消旧提醒。Worker 用 FOR UPDATE SKIP LOCKED 抢 Outbox，投递是 at-least-once；delivery 唯一键防重复尝试行，但不能宣称外部邮件/飞书 exactly-once。\n匿名、无会话且无工具轨迹的 grounded 回答才可进入按页面/项目隔离的语义缓存，阈值 0.94、TTL 600 秒、最多 100 条且不存问题明文；知识增删会整体失效。LLM 与 Reranker 用 Redis Lua共享 closed/open/half-open 状态和单恢复探针，Redis 失联退回本地 breaker。真实 PG/Redis测试覆盖十轮抢 Slot、改期竞争、自动过期和跨实例熔断；正式域名、远端 CI 与完整观测栈smoke 仍是上线验收项。",
    "behavior-stories.md": "# 行为故事、协作与职业动机\n我偏好先设计后编码，重视可观测性、可演进性与契约测试；失败记录是证据而不是污点。实习中用一对一演示、任务拆分和验收帮助同事学习 Figma 与 MQTT；当设计稿和小程序组件体系冲突时，我列出转换成本，与产品和设计先对齐核心页面再迭代。三个重要教训是：配置漂移要靠确定性评测暴露；ClickHouse 静默空结果说明零报错不等于正确；性能修复到时间边界仍未达标时应登记风险而不是修改口径。科班背景加上 2023 年起使用 AI 工具开发，让我逐步从实现功能转向思考架构、契约和交付，目标是 AI 全栈并长期向架构师发展。\n\n我最有成就感的一段工程经历，是建立了一套可复现、可交接的确定性验证闭环：84/84 条工程用例全绿，三轮 Kafka 重平衡共处理 18,720 个事件且零丢失，dbt 对 5.6 万行数据完成精确去重。我的核心贡献是把评测、故障注入、数据校验和结果留痕串成统一证据链；这些结果不仅能演示，也能被复跑、被核验并交给下一位工程师继续维护。\n\n## 慧眼识蚁竞赛\n挑战杯科技发明制作 A 类作品，团队 5 人，我任第一作者/申报者代表。方案用 CNN/GANs 辅助红火蚁识别与蚁巢估算，以多传感器、GPS 和环境感知支持巡检投药，并用时间序列与 MoE 预测繁殖迁徙趋势。完成实物原型和实测；识别准确率 ≥95% 是申报目标而非已证实实测结果，相关专利属于学校。",
}
if len(CANONICAL_CORPUS) != 20:
    raise RuntimeError("canonical corpus must contain exactly 20 documents")
